const twilio = require('twilio');
const axios = require('axios');

function normalizeIndianMobile(mobile) {
  const trimmed = String(mobile || '').trim();
  const digits = trimmed.replace(/[^0-9+]/g, '');
  if (digits.startsWith('+')) return digits;
  // assume Indian 10-digit
  if (/^\d{10}$/.test(digits)) return `+91${digits}`;
  return digits;
}

// Strip to 10 digits for Fast2SMS (no country code)
function stripToTenDigits(mobile) {
  const trimmed = String(mobile || '').trim();
  const digits = trimmed.replace(/\D/g, '');
  if (digits.length >= 10) return digits.slice(-10);
  return digits;
}

function createOtpProvider() {
  const provider = (process.env.OTP_PROVIDER || 'mock').toLowerCase();

  // ─── 2Factor.in ───────────────────────────────────────────────────────────
  if (provider === '2factor') {
    const apiKey = process.env.TWO_FACTOR_API_KEY;
    if (!apiKey) throw new Error('Missing TWO_FACTOR_API_KEY in environment variables');

    return {
      async sendOtp(mobile, code) {
        const number = stripToTenDigits(mobile);
        console.log(`[2Factor] Sending OTP to number: ${number}`);
        try {
          const url = `https://2factor.in/API/V1/${apiKey}/SMS/${number}/${String(code)}/OTP1`;
          const response = await axios.get(url, { timeout: 10000 });
          const data = response.data;
          console.log('[2Factor] Response:', JSON.stringify(data));
          if (data.Status !== 'Success') {
            throw new Error(`2Factor send failed: ${JSON.stringify(data)}`);
          }
        } catch (err) {
          const errBody = err.response?.data ? JSON.stringify(err.response.data) : err.message;
          console.error('[2Factor] SEND ERROR:', errBody);
          throw new Error(`2Factor error: ${errBody}`);
        }
      },

      async verifyOtp(mobile, code, storedHash) {
        const bcrypt = require('bcryptjs');
        if (!storedHash) return false;
        return bcrypt.compare(String(code), storedHash);
      },

      mode: '2factor',
    };
  }


  // ─── Fast2SMS ──────────────────────────────────────────────────────────────
  if (provider === 'fast2sms') {
    const apiKey = process.env.FAST2SMS_API_KEY;
    if (!apiKey) {
      throw new Error('Missing FAST2SMS_API_KEY in environment variables');
    }

    return {
      /**
       * Sends OTP via Fast2SMS OTP route.
       * The OTP is generated by auth.js and passed here.
       * Fast2SMS OTP route uses a pre-approved template with {#var#} placeholder.
       */
      async sendOtp(mobile, code) {
        const number = stripToTenDigits(mobile);
        console.log(`[Fast2SMS] Sending OTP to number: ${number}`);

        try {
          const response = await axios.get(
            'https://www.fast2sms.com/dev/bulkV2',
            {
              params: {
                authorization: apiKey,
                route: 'q',
                message: `Your Sanyog Certify OTP is ${String(code)}. Valid for 10 minutes. Do not share this code with anyone.`,
                numbers: number,
                flash: '0',
              },
              timeout: 10000,
            }
          );

          const data = response.data;
          console.log('[Fast2SMS] Response:', JSON.stringify(data));

          if (!data.return) {
            throw new Error(`Fast2SMS rejected: ${JSON.stringify(data)}`);
          }
        } catch (err) {
          // Log the actual Fast2SMS error body, not just the HTTP status
          const errBody = err.response?.data
            ? JSON.stringify(err.response.data)
            : err.message;
          console.error('[Fast2SMS] SEND ERROR:', errBody);
          throw new Error(`Fast2SMS error: ${errBody}`);
        }
      },

      /**
       * Verification is done by comparing with the bcrypt-hashed OTP stored in DB.
       * (Fast2SMS does not have a server-side verify endpoint for OTP route)
       */
      async verifyOtp(mobile, code, storedHash) {
        const bcrypt = require('bcryptjs');
        if (!storedHash) return false;
        return bcrypt.compare(String(code), storedHash);
      },

      mode: 'fast2sms',
    };
  }

  // ─── MSG91 ────────────────────────────────────────────────────────────────
  if (provider === 'msg91') {
    const authKey = process.env.MSG91_AUTH_KEY;
    if (!authKey) throw new Error('Missing MSG91_AUTH_KEY in environment variables');
    const templateId = process.env.MSG91_TEMPLATE_ID || '';

    return {
      async sendOtp(mobile, code) {
        const number = `91${stripToTenDigits(mobile)}`;
        console.log(`[MSG91] Sending OTP to: ${number}`);
        try {
          const payload = {
            mobile: number,
            otp: String(code),
          };
          if (templateId) payload.template_id = templateId;

          const response = await axios.post(
            'https://control.msg91.com/api/v5/otp',
            payload,
            {
              headers: {
                authkey: authKey,
                'Content-Type': 'application/json',
                Accept: 'application/json',
              },
              timeout: 10000,
            }
          );
          console.log('[MSG91] Response:', JSON.stringify(response.data));
          if (response.data?.type === 'error') {
            throw new Error(`MSG91 error: ${JSON.stringify(response.data)}`);
          }
        } catch (err) {
          const errBody = err.response?.data ? JSON.stringify(err.response.data) : err.message;
          console.error('[MSG91] SEND ERROR:', errBody);
          throw new Error(`MSG91 error: ${errBody}`);
        }
      },

      async verifyOtp(mobile, code, storedHash) {
        const bcrypt = require('bcryptjs');
        if (!storedHash) return false;
        return bcrypt.compare(String(code), storedHash);
      },

      mode: 'msg91',
    };
  }


  // ─── Twilio Verify ────────────────────────────────────────────────────────
  if (provider === 'twilio_verify') {
    const accountSid = process.env.TWILIO_ACCOUNT_SID;
    const authToken = process.env.TWILIO_AUTH_TOKEN;
    const serviceSid = process.env.TWILIO_VERIFY_SERVICE_SID;
    if (!accountSid || !authToken || !serviceSid) {
      throw new Error('Missing Twilio Verify env vars');
    }

    const client = twilio(accountSid, authToken);

    return {
      async sendOtp(mobile) {
        const to = normalizeIndianMobile(mobile);
        await client.verify.v2.services(serviceSid).verifications.create({ to, channel: 'sms' });
      },
      async verifyOtp(mobile, code) {
        const to = normalizeIndianMobile(mobile);
        const result = await client.verify.v2.services(serviceSid).verificationChecks.create({ to, code });
        return result.status === 'approved';
      },
      mode: 'twilio_verify',
    };
  }

  // ─── Mock (dev only) ──────────────────────────────────────────────────────
  return {
    async sendOtp(mobile, code) {
      console.log(`[OTP:mock] ✅ mobile=${mobile} code=${code}`);
      console.log(`[OTP:mock] ⚠️  Set OTP_PROVIDER=fast2sms and FAST2SMS_API_KEY for real SMS`);
    },
    async verifyOtp(mobile, code) {
      const test = process.env.OTP_TEST_CODE || '123456';
      return String(code) === String(test);
    },
    mode: 'mock',
  };
}

module.exports = { createOtpProvider, normalizeIndianMobile };
