/**
 * Sanyog Conformity – Mock Data
 * Comprehensive mock data from the actual Sanyog Conformity website services.
 */
import { palette } from '../theme/colors';
import type {
  ServiceCategory,
  Certification,
  Application,
  Notification,
  UserProfile,
} from '../types';

// ─── Service Categories ───────────────────────────────────
export const mockCategories: ServiceCategory[] = [
  {
    id: 'international',
    name: 'International Certifications',
    icon: 'globe',
    description: 'Global compliance for export markets — Saudi, EU, Africa, US & more',
    serviceCount: 24,
    gradient: palette.gradientBlue,
  },
  {
    id: 'domestic',
    name: 'Domestic Certifications',
    icon: 'shield-checkmark',
    description: 'Indian regulatory compliance — BIS, ISO, WPC, FSSAI, CDSCO & more',
    serviceCount: 20,
    gradient: palette.gradientPurple,
  },
  {
    id: 'testing',
    name: 'Testing Services',
    icon: 'flask',
    description: 'Accredited lab testing — Textiles, Electronics, Food, RoHS & more',
    serviceCount: 11,
    gradient: palette.gradientEmerald,
  },
  {
    id: 'inspection',
    name: 'Inspection Services',
    icon: 'search',
    description: 'Pre-shipment, container, vehicle & food inspections',
    serviceCount: 5,
    gradient: palette.gradientGold,
  },
];

// ─── Certifications ──────────────────────────────────────
export const mockCertifications: Certification[] = [
  // International
  {
    id: 'saso-cert',
    name: 'SASO Certification',
    slug: 'saso-certification',
    categoryId: 'international',
    categoryName: 'International',
    shortDescription: 'Saudi Standards, Metrology and Quality Organization certification for export to Saudi Arabia.',
    fullDescription: 'SASO certification ensures products comply with Saudi Arabia\'s quality and safety standards. Required for all goods being exported to Saudi Arabia, it covers a wide range of products from electronics to food items.',
    processDuration: '15-30 days',
    requiredDocuments: ['Product Test Reports', 'Bill of Materials', 'Product Photos', 'Company Registration', 'ISO Certificate (if any)'],
    processSteps: ['Submit product details', 'Lab testing & report', 'Documentation review', 'Certificate issuance'],
    isFeatured: true,
    isPopular: true,
    tags: ['Saudi Arabia', 'Export', 'Mandatory'],
  },
  {
    id: 'saber-cert',
    name: 'SABER Certification',
    slug: 'saber-certification',
    categoryId: 'international',
    categoryName: 'International',
    shortDescription: 'Saudi Arabia\'s online portal for product conformity — SABER Product & Shipment certificates.',
    fullDescription: 'SABER is the electronic system by SASO to issue product and shipment certificates. Both the Product Certificate of Conformity (PCoC) and Shipment Certificate of Conformity (SCoC) are obtained through this system.',
    processDuration: '5-15 days',
    requiredDocuments: ['Product Test Report', 'Commercial Invoice', 'Packing List', 'HS Code Details'],
    processSteps: ['Register on SABER portal', 'Submit product info', 'Assessment & testing', 'Certificate generation'],
    isFeatured: true,
    isPopular: true,
    tags: ['Saudi Arabia', 'SASO', 'Digital'],
  },
  {
    id: 'ce-marking',
    name: 'CE Marking',
    slug: 'ce-marking',
    categoryId: 'international',
    categoryName: 'International',
    shortDescription: 'European Conformity marking for products sold within the European Economic Area.',
    fullDescription: 'CE Marking indicates that a product meets EU health, safety, and environmental requirements. It is mandatory for many products sold in the EU, EEA, and Turkey.',
    processDuration: '30-60 days',
    requiredDocuments: ['Technical Documentation', 'Product Test Reports', 'Risk Assessment', 'Declaration of Conformity'],
    processSteps: ['Identify applicable directives', 'Product testing', 'Documentation preparation', 'Declaration & marking'],
    isFeatured: true,
    isPopular: false,
    tags: ['Europe', 'EU', 'Mandatory'],
  },
  {
    id: 'gmark-cert',
    name: 'G-Mark Certification (GCC)',
    slug: 'g-mark-certification',
    categoryId: 'international',
    categoryName: 'International',
    shortDescription: 'Gulf Conformity mark for products traded within the GCC member states.',
    fullDescription: 'The G-Mark ensures products meet the GCC Standardization Organization (GSO) Technical Regulations, facilitating trade across Gulf Cooperation Council nations.',
    processDuration: '20-45 days',
    requiredDocuments: ['Test Reports', 'Technical File', 'Product Specs', 'Factory Audit Report'],
    processSteps: ['Product classification', 'Testing at accredited lab', 'Documentation review', 'G-Mark issuance'],
    isFeatured: false,
    isPopular: true,
    tags: ['GCC', 'Gulf', 'Export'],
  },
  {
    id: 'reach-cert',
    name: 'REACH Compliance',
    slug: 'reach',
    categoryId: 'international',
    categoryName: 'International',
    shortDescription: 'Registration, Evaluation, Authorisation & Restriction of Chemicals — EU regulation.',
    fullDescription: 'REACH is a regulation of the European Union that addresses the production and use of chemical substances. Compliance ensures safe handling and documentation of chemicals in products.',
    processDuration: '30-90 days',
    requiredDocuments: ['Material Safety Data Sheets', 'Chemical Analysis Reports', 'Supply Chain Info', 'Product Composition'],
    processSteps: ['Substance identification', 'Chemical testing', 'Registration dossier', 'Compliance declaration'],
    isFeatured: false,
    isPopular: false,
    tags: ['EU', 'Chemicals', 'REACH'],
  },
  {
    id: 'usfda-cert',
    name: 'USFDA / FDA Registration',
    slug: 'usfda-fda-registration',
    categoryId: 'international',
    categoryName: 'International',
    shortDescription: 'US Food and Drug Administration registration for food, drugs, cosmetics & devices.',
    fullDescription: 'FDA Registration is mandatory for companies exporting food products, dietary supplements, drugs, cosmetics, and medical devices to the United States.',
    processDuration: '15-45 days',
    requiredDocuments: ['Product Labels', 'Nutritional Info', 'Manufacturing Process', 'DUNS Number'],
    processSteps: ['DUNS registration', 'FDA portal registration', 'Product listing', 'Agent designation'],
    isFeatured: true,
    isPopular: true,
    tags: ['USA', 'FDA', 'Food', 'Medical'],
  },
  {
    id: 'ecas-cert',
    name: 'ECAS / MOIAT Certification',
    slug: 'ecas-moiat-certification',
    categoryId: 'international',
    categoryName: 'International',
    shortDescription: 'Emirates Conformity Assessment Scheme for products exported to the UAE.',
    fullDescription: 'ECAS certification ensures products comply with UAE technical regulations. Mandatory for specific product categories entering the UAE market.',
    processDuration: '20-40 days',
    requiredDocuments: ['Product Test Reports', 'Technical Documents', 'Commercial Invoice', 'Packaging Details'],
    processSteps: ['Product classification', 'Testing & evaluation', 'Documentation submission', 'Certificate issuance'],
    isFeatured: false,
    isPopular: false,
    tags: ['UAE', 'Emirates', 'Export'],
  },
  // Domestic
  {
    id: 'bis-cert',
    name: 'BIS Certification',
    slug: 'bis-certification',
    categoryId: 'domestic',
    categoryName: 'Domestic',
    shortDescription: 'Bureau of Indian Standards certification — ISI, CRS, FMCS & Scheme X.',
    fullDescription: 'BIS Certification covers multiple schemes including ISI Mark for quality assurance, CRS for electronics, FMCS for foreign manufacturers, and Scheme X for specialized products. Mandatory for many product categories in India.',
    processDuration: '30-90 days',
    requiredDocuments: ['Product Test Reports', 'Factory Layout', 'Quality Control Plan', 'Business License', 'Product Drawing'],
    processSteps: ['Application filing', 'Document review', 'Factory inspection', 'Product testing', 'License grant'],
    isFeatured: true,
    isPopular: true,
    tags: ['India', 'BIS', 'Mandatory', 'ISI'],
  },
  {
    id: 'iso-cert',
    name: 'ISO Certification',
    slug: 'iso-certification',
    categoryId: 'domestic',
    categoryName: 'Domestic',
    shortDescription: 'International Organization for Standardization — ISO 9001, 14001, 22000, 45001.',
    fullDescription: 'ISO Certification demonstrates your organization follows internationally recognized quality management systems. We help with ISO 9001 (Quality), ISO 14001 (Environment), ISO 22000 (Food Safety), and ISO 45001 (Safety).',
    processDuration: '30-60 days',
    requiredDocuments: ['Company Profile', 'Process Documentation', 'Quality Manual', 'Management Review Records'],
    processSteps: ['Gap analysis', 'Documentation', 'Implementation', 'Internal audit', 'Certification audit'],
    isFeatured: true,
    isPopular: true,
    tags: ['ISO', 'Quality', 'Global'],
  },
  {
    id: 'wpc-cert',
    name: 'WPC Certification',
    slug: 'wpc-certification',
    categoryId: 'domestic',
    categoryName: 'Domestic',
    shortDescription: 'Wireless Planning & Coordination Wing approval for RF equipment in India.',
    fullDescription: 'WPC certification is required for importing or using wireless and radio frequency equipment in India. The approval ensures devices comply with India\'s spectrum management regulations.',
    processDuration: '15-45 days',
    requiredDocuments: ['Product Technical Details', 'RF Test Reports', 'Frequency Details', 'Import License'],
    processSteps: ['Application submission', 'Technical review', 'Frequency assignment', 'ETA issuance'],
    isFeatured: false,
    isPopular: true,
    tags: ['India', 'Wireless', 'RF'],
  },
  {
    id: 'epr-cert',
    name: 'EPR Registration',
    slug: 'epr-registration',
    categoryId: 'domestic',
    categoryName: 'Domestic',
    shortDescription: 'Extended Producer Responsibility for E-waste, plastic waste & battery waste management.',
    fullDescription: 'EPR Registration makes producers responsible for environmentally sound management of their products\' end-of-life. Covers e-waste, plastic waste, and battery waste under CPCB regulations.',
    processDuration: '30-60 days',
    requiredDocuments: ['Company PAN Card', 'GST Certificate', 'Product Details', 'Waste Management Plan'],
    processSteps: ['CPCB portal registration', 'Documentation submission', 'Verification', 'EPR authorization'],
    isFeatured: true,
    isPopular: true,
    tags: ['India', 'Environment', 'E-waste'],
  },
  {
    id: 'fssai-cert',
    name: 'FSSAI Registration',
    slug: 'fssai-registration',
    categoryId: 'domestic',
    categoryName: 'Domestic',
    shortDescription: 'Food Safety and Standards Authority of India license for food businesses.',
    fullDescription: 'FSSAI Registration/License is mandatory for all food businesses in India. It ensures food products meet safety and quality standards set by the Food Safety and Standards Authority of India.',
    processDuration: '7-30 days',
    requiredDocuments: ['Identity Proof', 'Address Proof', 'Food Category Details', 'Layout Plan', 'Water Test Report'],
    processSteps: ['Category identification', 'Online application', 'Document upload', 'Inspection (if needed)', 'License issuance'],
    isFeatured: false,
    isPopular: true,
    tags: ['India', 'Food', 'FSSAI'],
  },
  {
    id: 'cdsco-cert',
    name: 'CDSCO Registration',
    slug: 'cdsco-registration',
    categoryId: 'domestic',
    categoryName: 'Domestic',
    shortDescription: 'Central Drugs Standard Control Organisation approval for drugs & medical devices.',
    fullDescription: 'CDSCO registration is required for manufacturing, importing, and selling drugs and medical devices in India. It ensures product safety, efficacy, and quality.',
    processDuration: '30-120 days',
    requiredDocuments: ['Product Master File', 'Clinical Data', 'Manufacturing License', 'Quality Certificates'],
    processSteps: ['Product classification', 'Application filing', 'Technical review', 'Clinical evaluation', 'License grant'],
    isFeatured: false,
    isPopular: false,
    tags: ['India', 'Medical', 'Drugs'],
  },
  // Testing
  {
    id: 'textile-test',
    name: 'Textile Testing',
    slug: 'textile-testing',
    categoryId: 'testing',
    categoryName: 'Testing',
    shortDescription: 'Comprehensive textile testing for fibers, fabrics, garments & home textiles.',
    fullDescription: 'Our accredited labs provide comprehensive textile testing including tensile strength, colorfastness, shrinkage, pilling resistance, dimensional stability, and chemical analysis.',
    processDuration: '5-15 days',
    requiredDocuments: ['Sample Submission Form', 'Product Specs', 'Required Standard Details'],
    processSteps: ['Sample submission', 'Test method selection', 'Laboratory testing', 'Report generation'],
    isFeatured: false,
    isPopular: false,
    tags: ['Testing', 'Textile', 'Lab'],
  },
  {
    id: 'electrical-test',
    name: 'Electrical & Electronics Testing',
    slug: 'electrical-electronics-testing',
    categoryId: 'testing',
    categoryName: 'Testing',
    shortDescription: 'Safety & performance testing for electrical and electronic products.',
    fullDescription: 'Complete testing services for electrical safety, EMC compatibility, performance verification, and energy efficiency of electronic products as per IEC, IS, and EN standards.',
    processDuration: '7-21 days',
    requiredDocuments: ['Product Sample', 'Circuit Diagram', 'User Manual', 'Bill of Materials'],
    processSteps: ['Sample receipt', 'Test planning', 'Electrical safety testing', 'EMC testing', 'Report issuance'],
    isFeatured: false,
    isPopular: true,
    tags: ['Testing', 'Electronics', 'Safety'],
  },
  {
    id: 'rohs-test',
    name: 'RoHS Testing',
    slug: 'rohs',
    categoryId: 'testing',
    categoryName: 'Testing',
    shortDescription: 'Restriction of Hazardous Substances testing for electronics & electrical equipment.',
    fullDescription: 'RoHS testing verifies that products comply with restrictions on lead, mercury, cadmium, hexavalent chromium, PBBs, and PBDEs. Essential for EU and India market access.',
    processDuration: '5-10 days',
    requiredDocuments: ['Product Samples', 'Material Composition', 'Component List'],
    processSteps: ['Sample preparation', 'XRF screening', 'Detailed chemical analysis', 'Compliance report'],
    isFeatured: false,
    isPopular: false,
    tags: ['Testing', 'RoHS', 'Chemical'],
  },
  // Inspection
  {
    id: 'pre-shipment',
    name: 'Pre-Shipment Inspection',
    slug: 'pre-shipment-inspection',
    categoryId: 'inspection',
    categoryName: 'Inspection',
    shortDescription: 'Quality and quantity verification before goods leave the factory.',
    fullDescription: 'Pre-Shipment Inspection (PSI) is a crucial quality check performed on goods before they are shipped. Our inspectors verify product quality, quantity, packing, and labeling compliance.',
    processDuration: '2-5 days',
    requiredDocuments: ['Purchase Order', 'Product Specs', 'AQL Details', 'Shipping Schedule'],
    processSteps: ['Inspection booking', 'Factory visit', 'Quality check', 'Inspection report'],
    isFeatured: false,
    isPopular: false,
    tags: ['Inspection', 'Quality', 'Export'],
  },
];

// ─── Mock Applications ───────────────────────────────────
export const mockApplications: Application[] = [
  {
    id: 'app-001',
    certId: 'bis-cert',
    certName: 'BIS Certification (CRS)',
    categoryName: 'Domestic',
    companyName: 'TechVista Electronics Pvt. Ltd.',
    applicantName: 'Rahul Sharma',
    email: 'rahul@techvista.in',
    status: 'under_review',
    statusHistory: [
      { status: 'draft', date: '2026-02-15T10:30:00Z', note: 'Application drafted' },
      { status: 'submitted', date: '2026-02-16T09:00:00Z', note: 'Application submitted with all documents' },
      { status: 'under_review', date: '2026-02-20T14:30:00Z', note: 'Assigned to review officer' },
    ],
    documents: [
      { id: 'doc-1', name: 'Test_Report_CRS.pdf', type: 'pdf', uploadedAt: '2026-02-16T09:00:00Z', size: '2.4 MB' },
      { id: 'doc-2', name: 'Factory_Layout.pdf', type: 'pdf', uploadedAt: '2026-02-16T09:05:00Z', size: '1.1 MB' },
      { id: 'doc-3', name: 'Product_Drawing.dwg', type: 'dwg', uploadedAt: '2026-02-16T09:10:00Z', size: '850 KB' },
    ],
    remarks: 'Factory inspection scheduled for next week.',
    createdAt: '2026-02-15T10:30:00Z',
    updatedAt: '2026-02-20T14:30:00Z',
  },
  {
    id: 'app-002',
    certId: 'saber-cert',
    certName: 'SABER Certification',
    categoryName: 'International',
    companyName: 'TechVista Electronics Pvt. Ltd.',
    applicantName: 'Rahul Sharma',
    email: 'rahul@techvista.in',
    status: 'approved',
    statusHistory: [
      { status: 'draft', date: '2026-01-10T11:00:00Z', note: 'Application initiated' },
      { status: 'submitted', date: '2026-01-11T08:00:00Z', note: 'All documents submitted' },
      { status: 'under_review', date: '2026-01-15T10:00:00Z', note: 'Under technical review' },
      { status: 'approved', date: '2026-01-28T16:00:00Z', note: 'Certificate issued – valid until Jan 2027' },
    ],
    documents: [
      { id: 'doc-4', name: 'SABER_Test_Report.pdf', type: 'pdf', uploadedAt: '2026-01-11T08:00:00Z', size: '3.2 MB' },
      { id: 'doc-5', name: 'Commercial_Invoice.pdf', type: 'pdf', uploadedAt: '2026-01-11T08:05:00Z', size: '450 KB' },
    ],
    remarks: 'Certificate SABER-2026-4521 issued successfully.',
    createdAt: '2026-01-10T11:00:00Z',
    updatedAt: '2026-01-28T16:00:00Z',
  },
  {
    id: 'app-003',
    certId: 'epr-cert',
    certName: 'EPR Registration',
    categoryName: 'Domestic',
    companyName: 'TechVista Electronics Pvt. Ltd.',
    applicantName: 'Rahul Sharma',
    email: 'rahul@techvista.in',
    status: 'documents_required',
    statusHistory: [
      { status: 'draft', date: '2026-03-01T09:00:00Z', note: 'Application created' },
      { status: 'submitted', date: '2026-03-02T10:00:00Z', note: 'Submitted for review' },
      { status: 'documents_required', date: '2026-03-10T11:30:00Z', note: 'Additional waste management plan required' },
    ],
    documents: [
      { id: 'doc-6', name: 'Company_Registration.pdf', type: 'pdf', uploadedAt: '2026-03-02T10:00:00Z', size: '1.8 MB' },
    ],
    remarks: 'Please upload a detailed waste management plan and recycler authorization.',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-03-10T11:30:00Z',
  },
  {
    id: 'app-004',
    certId: 'iso-cert',
    certName: 'ISO 9001:2015',
    categoryName: 'Domestic',
    companyName: 'TechVista Electronics Pvt. Ltd.',
    applicantName: 'Rahul Sharma',
    email: 'rahul@techvista.in',
    status: 'submitted',
    statusHistory: [
      { status: 'draft', date: '2026-03-25T14:00:00Z', note: 'Draft created' },
      { status: 'submitted', date: '2026-03-26T09:30:00Z', note: 'Application submitted' },
    ],
    documents: [
      { id: 'doc-7', name: 'Quality_Manual.pdf', type: 'pdf', uploadedAt: '2026-03-26T09:30:00Z', size: '5.6 MB' },
      { id: 'doc-8', name: 'Process_Map.pdf', type: 'pdf', uploadedAt: '2026-03-26T09:35:00Z', size: '2.1 MB' },
    ],
    remarks: '',
    createdAt: '2026-03-25T14:00:00Z',
    updatedAt: '2026-03-26T09:30:00Z',
  },
];

// ─── Mock Notifications ──────────────────────────────────
export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    title: 'Application Under Review',
    message: 'Your BIS Certification (CRS) application is now being reviewed by our team.',
    type: 'info',
    read: false,
    createdAt: '2026-03-30T14:30:00Z',
    appId: 'app-001',
  },
  {
    id: 'notif-002',
    title: 'Documents Required',
    message: 'Your EPR Registration needs additional documents. Please upload a waste management plan.',
    type: 'warning',
    read: false,
    createdAt: '2026-03-28T11:30:00Z',
    appId: 'app-003',
  },
  {
    id: 'notif-003',
    title: 'Certificate Approved! 🎉',
    message: 'Your SABER Certification has been approved. Certificate number: SABER-2026-4521.',
    type: 'success',
    read: true,
    createdAt: '2026-03-20T16:00:00Z',
    appId: 'app-002',
  },
  {
    id: 'notif-004',
    title: 'New Service Available',
    message: 'We now offer G-Mark Certification for GCC markets. Check it out in our services catalog.',
    type: 'info',
    read: true,
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'notif-005',
    title: 'Application Submitted',
    message: 'Your ISO 9001:2015 application has been submitted successfully.',
    type: 'success',
    read: false,
    createdAt: '2026-03-26T09:30:00Z',
    appId: 'app-004',
  },
];

// ─── Mock User Profile ───────────────────────────────────
export const mockUser: UserProfile = {
  id: 'user-001',
  name: 'Rahul Sharma',
  email: 'rahul@techvista.in',
  phone: '+91 98765 43210',
  company: 'TechVista Electronics Pvt. Ltd.',
};
